### ISSUE TITLE
when i used redhat director image which also used ironic discovery, it will cause IMM of lenovo system x3650  disconnetion

### ISSUE THREAD

**Issue by yixuan178** [rdo-management/ironic-discoverd#4]
when we do redhat osp8 on lenovo system x, many times we face one issue that 'bulk start' command will broken connection IMM, from my desktop, i cannot ping it, i need reboot that machine by manual. then ip can be pingable. 

[stack@director63 ~]$ rpm -qa|grep rhosp
rhosp-director-images-8.0-20160603.2.el7ost.noarch
rhosp-director-images-ipa-8.0-20160603.2.el7ost.noarch

**Comment by cybertron** [comment]
This repo is no longer being maintained, and OSP bugs are tracked on bugzilla: https://bugzilla.redhat.com/  Please open a bz there for your issue.  Thanks.

Direct link to open a bz against OSP: https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20OpenStack  Probably just use the rhel-osp-director component.

**Comment by yixuan178** [comment]
hello @cybertron , do you know if osp8 discovery image used that repo to send ipmi command, and where can i review that repo? thanks!

**Comment by cybertron** [comment]
Ironic is the service responsible for sending IPMI commands: https://github.com/openstack/ironic
